routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('learnerplans','LearningPlansController');

app/Competency.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Competency extends Model
{
    public function course(){
        return $this->belongsTo(Course::class);
    }
}

app/Course.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Course extends Model
{
    public function learningplan(){
        return $this->belongsTo(LearningPlan::class);
    }

    public function competency(){
        return $this->hasOne(Competency::class);
    }
}

app/Learner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Learner extends Model
{
    public function learningplan(){
        return $this->belongsTo(LearningPlan::class);
    }

    public function roles(){
        return $this->hasMany(Role::class);
    }

}

app/LearningPlan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class LearningPlan extends Model
{

    protected $guarded = [];

    public function learner(){
        return $this->hasOne(Learner::class);
    }

    public function courses(){
        return $this->hasMany(Course::class);
    }

}

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    public function learner(){
        return $this->belongsTo(Learner::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/LearningPlansController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\LearningPlan;
use App\Course;
class LearningPlansController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {

        // dd('ll');

        if(request()->ajax())
        {
        
      
            return datatables()->of(LearningPlan::with(['Course','Competency'])->latest()->get())
 
                    ->addColumn('checkbox', function($data){
                        $checkbox = '<input type="checkbox" name="courses[]" class="pdr_checkbox" value="'.$data->id.'" />';
                        return $checkbox;
                    })

                    ->addColumn('closingdate', function($data){
                        if($data->id == ){

                        }
                        $checkbox = '<input type="checkbox" name="courses[]" class="pdr_checkbox" value="'.$data->id.'" />';
                        return $checkbox;
                    })
                    ->make(true);

        }
    
        return view('learnerplan');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Learner Plan') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" ></script>

    <!-- Fonts -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css" />
    <link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
        
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
 
        <main class="py-4">
        <div class="container">
            @yield('content')
            </div>
        </main>
    </div>
</body>
</html>

resources/views/learnerplan.blade.php
@extends('layouts.app')
@section('title','Learner Plan')
@section('content')



<div class="row">
        <div style="margin-left :10%;margin-right :10%;" >
          <div class="panel panel-default">
            <div class="panel-heading " >
                <div  >
                    <h3 class="panel-title "> Your Learning Plan  </h3>
                </div>
                <div >
                    <!-- <p><a class ="btn btn-primary" href="loads/create">Submit Load</a></p> -->
                </div>                
            </div>
            <div class="panel-body">

            <div class="table-responsive">
            <table class="table table-bordered table-striped" id="learningplan_table">
            <thead >
                <tr>
                  <th scope="col">Competency</th>
                  <th scope="col">Course Name</th>
                  <th scope="col">ID</th>
                  <th scope="col">Type</th>
                  <th scope="col">H:Min</th>
                  <th scope="col">Key</th>
                  <th scope="col">Description</th>
                  <th scope="col">Completed Planned Date</th>
                </tr>
            </thead>
        
            </table>  
            </div> 
            </div>
          </div>
        </div>
      </div>



   
  <script>
$(document).ready(function(){
    
 $('#learningplan_table').DataTable({
  processing: true,
  serverSide: true,
  ajax:{
   url: "{{ route('learnerplans.index') }}",
  },

 });

});
</script>
@endsection